# Generated by Django 3.1.7 on 2021-10-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback_app', '0004_remove_duser_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewee_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback_app.department')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
