# Generated by Django 3.1.7 on 2021-10-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_reviewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewees',
            old_name='user_id',
            new_name='UserReviewer',
        ),
        migrations.RenameField(
            model_name='reviewers',
            old_name='user_id',
            new_name='UserReviewee',
        ),
        migrations.AddField(
            model_name='reviewees',
            name='reviewee',
            field=models.ForeignKey(db_column='reviewee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback_app.duser', to_field='user'),
        ),
        migrations.AddField(
            model_name='reviewers',
            name='reviewer',
            field=models.ForeignKey(db_column='reviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback_app.duser', to_field='user'),
        ),
    ]
